#!/usr/bin/env ruby
require 'nmax'

if ARGV.size != 1 || ARGV.first.to_i <= 0
  puts  'Wrong arguments: cat FILE | nmax NUMBERS_COUNT'
  exit
end
numbers_finder = Nmax::Finder.new($stdin, ARGV.first.to_i)
max_numbers = numbers_finder.find
puts "\nNumbers: "
max_numbers.each do |number|
  puts number
end